### ISSUE TITLE
Productify Sailor 3.0.0

### ISSUE THREAD

**Issue by A3a3e1** [elasticio/sailor-jvm#50]
Already tested by platform QAs. We should test it from our side and push to Maven Central

**Comment by A3a3e1** [comment]
**Smoke test checklist**
- [ ] Push to platform
- [ ] Retrieve sample
- [ ] Retrieve sample on LA (if possible)
- [ ] Run keen flow
- [ ] Run realtime flow
- [ ] Create valid creds in the flow
- [ ] Create valid creds in credentials itself
- [ ] At least one valid input for each trigger/action
- [ ] At least one invalid input for each trigger/action

**Comment by stas-fomenko** [comment]
Issue detected: 
**Error is thrown on flow stop: `Component failed to start. See logs for additional information.`**

**Description:**
Error is thrown on ordinary/RT flow stop: `Component failed to start. See logs for additional information.` 

**STR:**
1. Start flow with petstore java component: Init Start Shutdown (Sailor 3.0.0) trigger
2. Stop flow.

**AR:** 3 Errors thrown on flow stop:
_Error:_
Reason: Error
Exit Code: 1
_Logs:_
```
[2020-03-30 15:33:45.092]: [INFO  tini (1)] Spawned child process '/run.sh' with pid '6'
[2020-03-30 15:33:45.092]: Starting application in apprunner...
[2020-03-30 15:33:45.096]: Starting slug download ...
[2020-03-30 15:33:46.027]: Successfully downloaded and extracted slug file
[2020-03-30 15:33:47.144]: 12:33:46,350 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/apprunner/build/elasticio/dependencies/sailor-jvm-3.0.0.jar!/logback.xml]
[2020-03-30 15:33:47.144]: 12:33:46,416 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1f28c152 - URL [jar:file:/home/apprunner/build/elasticio/dependencies/sailor-jvm-3.0.0.jar!/logback.xml] is not of type file
[2020-03-30 15:33:47.144]: 12:33:46,350 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
[2020-03-30 15:33:47.144]: 12:33:46,350 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
[2020-03-30 15:33:47.144]: 12:33:46,535 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
[2020-03-30 15:33:47.144]: 12:33:46,548 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
[2020-03-30 15:33:47.144]: 12:33:47,137 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
[2020-03-30 15:33:47.144]: (no message)
[2020-03-30 15:33:47.144]: 12:33:46,554 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
[2020-03-30 15:33:47.144]: 12:33:46,621 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@6:22 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][pattern]]
[2020-03-30 15:33:47.144]: 12:33:47,136 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
[2020-03-30 15:33:47.144]: 12:33:47,137 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
[2020-03-30 15:33:47.144]: 12:33:47,139 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7d907bac - Registering current configuration as safe fallback point
[2020-03-30 15:33:47.316]: About to init Sailor
[2020-03-30 15:33:47.938]: Component descriptor from classpath: /component.json
[2020-03-30 15:33:47.961]: Retrieving step data for user task-5e81bf26d6351c556fc7c561 at: https://api.elastic.io/v1/tasks/5e81bf26d6351c556fc7c561/steps/step_1
[2020-03-30 15:33:49.126]: Sending GET request to https://api.elastic.io/v1/tasks/5e81bf26d6351c556fc7c561/steps/step_1
[2020-03-30 15:33:49.800]: Got 200 response
[2020-03-30 15:33:49.804]: Successfully consumed response entity
[2020-03-30 15:33:49.812]: Shutting down component
[2020-03-30 15:33:49.812]: Function Java class to be instantiated: io.elastic.petstore.triggers.InitStartShutdownTrigger
[2020-03-30 15:33:49.813]: Instantiating component io.elastic.petstore.triggers.InitStartShutdownTrigger
[2020-03-30 15:33:49.815]: About to shut down the trigger
[2020-03-30 15:33:49.816]: Exception in thread "main" java.lang.NullPointerException
[2020-03-30 15:33:49.817]: at io.elastic.sailor.Sailor.shutdown(Sailor.java:153)
[2020-03-30 15:33:49.817]: at io.elastic.sailor.Sailor.createAndStartSailor(Sailor.java:43)
[2020-03-30 15:33:49.817]: at io.elastic.petstore.triggers.InitStartShutdownTrigger.shutdown(InitStartShutdownTrigger.java:50)
[2020-03-30 15:33:49.817]: at io.elastic.sailor.Sailor.startOrShutdown(Sailor.java:76)
[2020-03-30 15:33:49.817]: at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getInt(JsonObjectBuilderImpl.java:213)
[2020-03-30 15:33:49.817]: at io.elastic.sailor.Sailor.main(Sailor.java:30)
[2020-03-30 15:33:49.840]: [INFO  tini (1)] Main child exited normally (with status '1')
```

**ER:**
No errors are thrown on flow stop.

**Comment by stas-fomenko** [comment]
moved to stage by mistake

**Comment by A3a3e1** [comment]
The same behavior.
Logs from the last execution:
```
[2020-04-07 18:34:22.377]: [INFO  tini (1)] Spawned child process '/run.sh' with pid '6'
[2020-04-07 18:34:22.378]: Starting application in apprunner...
[2020-04-07 18:34:22.379]: Starting slug download ...
[2020-04-07 18:34:22.942]: Successfully downloaded and extracted slug file
[2020-04-07 18:34:23.789]: 15:34:23,182 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
[2020-04-07 18:34:23.789]: 15:34:23,198 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1f28c152 - URL [jar:file:/home/apprunner/build/elasticio/dependencies/sailor-jvm-3.0.0.jar!/logback.xml] is not of type file
[2020-04-07 18:34:23.789]: 15:34:23,783 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
[2020-04-07 18:34:23.789]: 15:34:23,317 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@6:22 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][pattern]]
[2020-04-07 18:34:23.789]: 15:34:23,784 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
[2020-04-07 18:34:23.789]: 15:34:23,785 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7d907bac - Registering current configuration as safe fallback point
[2020-04-07 18:34:23.789]: 15:34:23,309 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
[2020-04-07 18:34:23.789]: 15:34:23,306 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
[2020-04-07 18:34:23.789]: (no message)
[2020-04-07 18:34:23.789]: 15:34:23,297 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
[2020-04-07 18:34:23.789]: 15:34:23,182 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
[2020-04-07 18:34:23.789]: 15:34:23,183 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/apprunner/build/elasticio/dependencies/sailor-jvm-3.0.0.jar!/logback.xml]
[2020-04-07 18:34:23.789]: 15:34:23,783 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
[2020-04-07 18:34:23.840]: About to init Sailor
[2020-04-07 18:34:24.318]: Component descriptor from classpath: /component.json
[2020-04-07 18:34:24.381]: Retrieving step data for user task-5e8c880c926e41001142508d at: https://api.eio.ninja/v1/tasks/5e8c880c926e41001142508d/steps/step_1
[2020-04-07 18:34:25.103]: Sending GET request to https://api.eio.ninja/v1/tasks/5e8c880c926e41001142508d/steps/step_1
[2020-04-07 18:34:25.581]: Got 200 response
[2020-04-07 18:34:25.585]: Successfully consumed response entity
[2020-04-07 18:34:25.590]: Function Java class to be instantiated: io.elastic.petstore.triggers.InitStartShutdownTrigger
[2020-04-07 18:34:25.590]: Shutting down component
[2020-04-07 18:34:25.591]: Instantiating component io.elastic.petstore.triggers.InitStartShutdownTrigger
[2020-04-07 18:34:25.592]: sdjfhkuasdfhksdfh
[2020-04-07 18:34:25.598]: Sending DELETE request to https://api.eio.ninja/sailor-support/hooks/task/5e8c880c926e41001142508d/startup/data
[2020-04-07 18:34:25.678]: Got 204 response
[2020-04-07 18:34:25.680]: at io.elastic.sailor.impl.HttpUtils.delete(HttpUtils.java:108)
[2020-04-07 18:34:25.680]: Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Null response received
[2020-04-07 18:34:25.680]: at io.elastic.sailor.impl.ApiClientImpl.deleteStartupState(ApiClientImpl.java:89)
[2020-04-07 18:34:25.680]: at io.elastic.sailor.impl.HttpUtils.sendHttpRequest(HttpUtils.java:167)
[2020-04-07 18:34:25.680]: at io.elastic.sailor.Sailor.shutdown(Sailor.java:155)
[2020-04-07 18:34:25.680]: at io.elastic.sailor.Sailor.startOrShutdown(Sailor.java:76)
[2020-04-07 18:34:25.680]: at io.elastic.sailor.Sailor.main(Sailor.java:30)
[2020-04-07 18:34:25.680]: at io.elastic.sailor.Sailor.createAndStartSailor(Sailor.java:43)
[2020-04-07 18:34:25.680]: ... 6 more
[2020-04-07 18:34:25.680]: at io.elastic.sailor.impl.HttpUtils.sendHttpRequest(HttpUtils.java:158)
[2020-04-07 18:34:25.680]: Caused by: java.lang.RuntimeException: Null response received
[2020-04-07 18:34:25.690]: [INFO  tini (1)] Main child exited normally (with status '1')
```

**Comment by A3a3e1** [comment]
JVM Sailor 3.0.0 released
